# Generated by Django 3.1.7 on 2021-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_quantity',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
