# Generated by Django 3.1.7 on 2021-04-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210406_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='prod_id',
        ),
    ]
