# Generated by Django 3.1.7 on 2021-04-06 09:47

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('users', '0010_auto_20210406_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='address1',
            field=address.models.AddressField(default='', on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='address2',
            field=address.models.AddressField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
    ]
