# Generated by Django 3.1.7 on 2021-04-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210406_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_placed',
            new_name='order_placed',
        ),
    ]
