# Generated by Django 3.1.7 on 2021-04-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210406_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='address2',
        ),
        migrations.AddField(
            model_name='order',
            name='shippping_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
