# Generated by Django 3.1.7 on 2021-04-06 13:28

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210406_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='address',
        ),
        migrations.AddField(
            model_name='user_info',
            name='address1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user_info',
            name='address2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user_info',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_info',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='user_info',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user_info',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
