# Generated by Django 3.1.7 on 2021-04-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210406_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippping_info',
            new_name='shipping_info',
        ),
    ]
