# Generated by Django 3.1.7 on 2021-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(default='default.jpg', upload_to='product_back_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='colours_available',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.ImageField(default='default.jpg', upload_to='product_front_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_image_1',
            field=models.ImageField(default='default.jpg', upload_to='product_side_pics_1'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_image_2',
            field=models.ImageField(default='default.jpg', upload_to='product_side_pics_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_image',
            field=models.ImageField(default='default.jpg', upload_to='product_top_pics'),
        ),
    ]
