# Generated by Django 3.1.7 on 2021-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210407_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='image1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='default.jpg', upload_to='image4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='default.jpg', upload_to='image5'),
        ),
    ]
