# Generated by Django 3.1.7 on 2021-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210407_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
